version: '2'

volumes:
   pgdb:

services:
  redis:
    networks:
     - internal
    image: redis


  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    depends_on:
      - sentry
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - proxy-tier

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy

  smtp:
    image: "namshi/smtp"
    networks:
     - internal

  postgres:
    image: 'postgres:9.5'
    networks:
     - internal
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DBNAME: sentry
      POSTGRES_DBUSER: sentry
      POSTGRES_DBPASS: sentry
    volumes:
     - pgdb:/var/lib/postgresql/data

  sentry:
    image: sentry:latest
    depends_on:
     - redis
     - postgres
    links:
     - redis
     - postgres
    volumes:
     - ./conf:/etc/sentry
    env_file: 
     - sentry.env
     - vhost.env
    networks:
     - internal
     - proxy-tier
    environment:
      VIRTUAL_PORT: "9000"
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: postgres
      SENTRY_DB_PASSWORD: postgres
      SENTRY_REDIS_HOST: redis
      SENTRY_EMAIL_HOST: smtp

  sentry_celery_beat:
    image: sentry:latest
    networks:
     - internal
    depends_on:
     - redis
     - postgres
    command: "sentry run cron --pidfile=/tmp/celerybeat-sentry.pid"
    env_file: sentry.env
    environment:
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: postgres
      SENTRY_DB_PASSWORD: postgres
      SENTRY_REDIS_HOST: redis

  sentry_celery_worker:
    image: sentry:latest
    networks:
     - internal
    depends_on:
     - redis
     - postgres
    command: "sentry run worker"
    env_file: sentry.env
    environment:
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: postgres
      SENTRY_DB_PASSWORD: postgres
      SENTRY_REDIS_HOST: redis

networks:
  proxy-tier:
  internal: 
